---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "git-clone-controller.fullname" . }}
rules:
    # parsing incoming requests
    - apiGroups:
          - ""
      resources:
          - pods
      verbs:
          - get
          - list
          #- update

    # injecting secrets into target namespace
    - apiGroups:
          - ""
      resources:
          - secrets
      verbs:
          - get
          - list
          - create
          - update
          - delete
          #- update

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "git-clone-controller.fullname" . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "git-clone-controller.fullname" . }}
subjects:
    - kind: ServiceAccount
      name: {{ include "git-clone-controller.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
