{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "git-clone-controller.serviceAccountName" . }}
    labels:
        {{- include "git-clone-controller.labels" . | nindent 8 }}
  {{- with .Values.serviceAccount.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
