---
apiVersion: v1
kind: Service
metadata:
    name: {{ include "git-clone-controller.fullname" . }}
    labels:
        {{- include "git-clone-controller.labels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: 8080
          targetPort: http
          protocol: TCP
          name: http

        - port: 4443
          targetPort: https
          protocol: TCP
          name: https
    selector:
        {{- include "git-clone-controller.selectorLabels" . | nindent 8 }}
