apiVersion: v1
kind: Pod
metadata:
    name: "tagged-pod"
    labels:
        riotkit.org/git-clone-controller: "true"
    annotations:
        git-clone-controller/revision: main
        git-clone-controller/url: "https://github.com/jenkins-x/go-scm"
        git-clone-controller/path: /workspace/source
        git-clone-controller/owner: "1000"
        git-clone-controller/group: "1000"
        git-clone-controller/secretName: git-secrets
        git-clone-controller/secretTokenKey: jenkins-x
spec:
    restartPolicy: Never
    automountServiceAccountToken: false
    containers:
        - command:
              - /bin/sh
              - "-c"
              - "find /workspace/source; ls -la /workspace/source"
          image: busybox:latest
          name: test
          volumeMounts:
              - mountPath: /workspace/source
                name: workspace
    volumes:
        - name: workspace
          emptyDir: {}
    securityContext:
        fsGroup: 1000
