---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-kubernetes-webhook
  name: simple-kubernetes-webhook
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 30100
  selector:
    app: simple-kubernetes-webhook
