
image:
    repository: ghcr.io/riotkit-org/git-clone-controller
    tag: "" # defaults to {{ .Release.appVersion }}

# Only namespaces that has label 'riotkit.org/git-clone-controller: true'
onlyLabelledNamespaces: false

tls:
    enabled: true
    createSecret: true
    secretName: "git-clone-controller-tls"
        
replicas: 1
podAnnotations: {}
podSecurityContext:
    runAsUser: 65161
    runAsGroup: 65161
    fsGroup: 65161
    runAsNonRoot: true

webhook:
    failurePolicy: Fail

serviceAccount:
    create: true
    name: git-clone-controller-sa
    annotations: {}

env:
    LOG_JSON: false
    LOG_LEVEL: debug

resources:
    requests:
        memory: 16Mi
        cpu: 0
    limits:
        memory: 128Mi
        cpu: 1

health:
    liveness:
        enabled: true
        attributes:
            failureThreshold: 1
    readiness:
        enabled: true
        attributes: {}

service:
    type: ClusterIP
    port: 8080
