name: Test and release
on:
    push:

jobs:
    build:
        uses: riotkit-org/.github/.github/workflows/go-kubernetes.release.yaml@main
        with:
            binaryName: git-clone-controller
            dockerImage: ghcr.io/riotkit-org/git-clone-controller
            sonarCloudEnabled: true
            dockerReleasingEnabled: true
            publishingHelmChartEnabled: true

        secrets:
            SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
            GH_RW_TOKEN: "${{ secrets.GH_RW_TOKEN }}"
