name: Test and release
on:
    push:

jobs:
    test-and-build:
        uses: riotkit-org/.github/pipelines/go/kubernetes-go/release.yaml@main
        with:
            binaryName: git-clone-controller
            dockerImage: ghcr.io/riotkit-org/git-clone-controller
