name: Test and release
on:
    push:
    workflow_dispatch:
        inputs: {}

jobs:
    build:
        uses: riotkit-org/.github/.github/workflows/build.go.yaml@release-1
        with:
            goVersion: "1.20"
            binaryName: "git-clone-controller"

#    test:
#        uses: riotkit-org/.github/.github/workflows/test.integration-tests.yaml@release-1
#        if: "!startsWith(github.ref, 'refs/tags/v')"
#        with:
#            osVariant: ubuntu-22.04
#            pythonEnabled: true
#            testReportEnabled: true
#            testReportPattern: kuttl-report.xml

    container-image:
        uses: riotkit-org/.github/.github/workflows/release.container.yaml@release-1
        needs: ["build"]
        if: |
            always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
        with:
            osVariant: ubuntu-22.04
            dockerImage: "ghcr.io/riotkit-org/git-clone-controller"

    helm:
        uses: riotkit-org/.github/.github/workflows/release.helm.yaml@release-1
        needs: ["container-image"]
        if: |
            always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
        with:
            chartPath: helm/git-clone-controller
            chartRepoName: "riotkit-org/charts/"
            chartName: git-clone-controller
            enableHelmDocs: true
